#!/bin/bash

trap 'kill $(jobs -p) 2>/dev/null' EXIT
if [[ $NODE_ENV != production ]]; then
  echo "    - starting mongodb ..."
  mongod --dbpath data 2>&1 >mongod.log &
  echo "    - starting redis ..."
  redis-server 2>&1 >redis.log &
  echo "    - starting worker ..."
  nodemon -q -w services services/worker.js &
  echo "    - starting engine and watching sources ..."
  echo
  nodemon -q -w services bin/webdesignio-engine.js -- run
else
  node bin/webdesignio-engine.js run
fi
